# frozen_string_literal: true

CERTIFIED_FRESH_EXCLUDED_MOVIE_TITLES = [
  "A Room with a View",
  "A Woman Under the Influence",
  "Atlantic City",
  "Butterfly Kisses",
  "Captain Blood",
  "Crshd",
  "Don't Talk to Irene",
  "Downhill Racer",
  "Dragonslayer",
  "Fat City",
  "Imitation of Life",
  "Living in Oblivion",
  "Love After Love",
  "Night of the Comet",
  "Odd Man Out",
  "Planet Terror",
  "Pretending I'm a Superman: The Tony Hawk Video Game Story",
  "Red River",
  "Room at the Top",
  "Slow Machine",
  "Story Ave",
  "The Fabulous Baker Boys",
  "The Hanging Garden",
  "The Man Who Would Be King",
  "The Naked Kiss",
  "Wildhood",
  "Winchester '73",
  "Written on the Wind",
  "Yes",
].to_set.freeze
