# frozen_string_literal: true

CERTIFIED_FRESH_EXCLUDED_MOVIE_TITLES = [
  "A Room with a View",
  "A Woman Under the Influence",
  "Atlantic City",
  "Butterfly Kisses",
  "Captain Blood",
  "Crshd",
  "Don't Talk to Irene",
  "Downhill Racer",
  "Dragonslayer",
  "Dreamcatcher",
  "Fat City",
  "Imitation of Life",
  "Living in Oblivion",
  "Love After Love",
  "Mali Blues",
  "Night of the Comet",
  "Oasis Knebworth 1996",
  "Odd Man Out",
  "Of Men and War",
  "Omette: Made in America",
  "Planet Terror",
  "Pretending I'm a Superman: The Tony Hawk Video Game Story",
  "Red River",
  "Room at the Top",
  "Slow Machine",
  "Story Ave",
  "The Fabulous Baker Boys",
  "The Hanging Garden",
  "The Killing of Kenneth Chamberlain",
  "The Man Who Would Be King",
  "The Naked Kiss",
  "Wildhood",
  "Winchester '73",
  "Written on the Wind",
  "Yes",
].to_set.freeze
