# frozen_string_literal: true

module Dewey
  CLASSES = {
    0 => "Computer Science & Information",
    100 => "Philosophy & Psychology",
    200 => "Religion",
    300 => "Social Sciences",
    400 => "Language",
    500 => "Science",
    600 => "Technology",
    700 => "Arts & Recreation",
    800 => "Literature",
    900 => "History & Geography",
  }.freeze

  DIVISIONS = {
    0 => "Computer Science & Information",
    10 => "Bibliography",
    20 => "Library & Information Science",
    30 => "Encyclopedias",
    40 => "Unassigned",
    50 => "Magazines & Journals",
    60 => "Associations & Organizations",
    70 => "News Media & Journalism",
    80 => "Quotations",
    90 => "Manuscripts & Rare Books",
    100 => "Philosophy",
    110 => "Metaphysics",
    120 => "Epistemology",
    130 => "Parapsychology & Occultism",
    140 => "Philosophical Schools",
    150 => "Psychology",
    160 => "Logic",
    170 => "Ethics",
    180 => "Ancient & Medieval Philosophy",
    190 => "Modern Western Philosophy",
    200 => "Religion",
    210 => "Philosophy of Religion",
    220 => "The Bible",
    230 => "Christianity",
    240 => "Christian Practice",
    250 => "Christian Ministry",
    260 => "Christian Organization",
    270 => "Church History",
    280 => "Christian Denominations",
    290 => "Other Religions",
    300 => "Social Sciences",
    310 => "Statistics",
    320 => "Political Science",
    330 => "Economics",
    340 => "Law",
    350 => "Public Administration",
    360 => "Social Services",
    370 => "Education",
    380 => "Commerce & Communications",
    390 => "Customs & Folklore",
    400 => "Language",
    410 => "Linguistics",
    420 => "English",
    430 => "German",
    440 => "French",
    450 => "Italian",
    460 => "Spanish & Portuguese",
    470 => "Latin",
    480 => "Greek",
    490 => "Other Languages",
    500 => "Science",
    510 => "Mathematics",
    520 => "Astronomy",
    530 => "Physics",
    540 => "Chemistry",
    550 => "Earth Sciences",
    560 => "Paleontology",
    570 => "Biology",
    580 => "Botany",
    590 => "Zoology",
    600 => "Technology",
    610 => "Medicine",
    620 => "Engineering",
    630 => "Agriculture",
    640 => "Home Economics",
    650 => "Management",
    660 => "Chemical Engineering",
    670 => "Manufacturing",
    680 => "Specific Manufacturing",
    690 => "Construction",
    700 => "Arts",
    710 => "Landscape & Urban Planning",
    720 => "Architecture",
    730 => "Sculpture",
    740 => "Drawing & Decorative Arts",
    750 => "Painting",
    760 => "Printmaking",
    770 => "Photography",
    780 => "Music",
    790 => "Sports & Recreation",
    800 => "Literature",
    810 => "American Literature",
    820 => "English Literature",
    830 => "German Literature",
    840 => "French Literature",
    850 => "Italian Literature",
    860 => "Spanish Literature",
    870 => "Latin Literature",
    880 => "Greek Literature",
    890 => "Other Literatures",
    900 => "History",
    910 => "Geography & Travel",
    920 => "Biography",
    930 => "Ancient World History",
    940 => "European History",
    950 => "Asian History",
    960 => "African History",
    970 => "North American History",
    980 => "South American History",
    990 => "Pacific Islands History",
  }.freeze

  def self.class_lookup(call_number)
    digits = call_number[/\A(\d+)/, 1]
    return "" unless digits

    CLASSES[digits.to_i / 100 * 100] || ""
  end

  def self.lookup(call_number)
    digits = call_number[/\A(\d+)/, 1]
    return "" unless digits

    DIVISIONS[digits.to_i / 10 * 10] || ""
  end
end
