# frozen_string_literal: true

EXCLUDED_MOVIE_TITLES = [
  "3 Women",
  "A Beautiful Day in the Neighborhood",
  "A Bread Factory, Part One",
  "A Hidden Life",
  "A Raisin in the Sun",
  "Ad Astra",
  "Anne at 13,000 Ft.",
  "Bang the Drum Slowly",
  "Barbie",
  "Ben-Hur",
  "Bergman Island",
  "Black Mother",
  "Black Sabbath",
  "Call Me Kuchu",
  "Can You Bring It: Bill T. Jones and D-Man in the Waters",
  "Cane River",
  "Children of a Lesser God",
  "Close Encounters of the Third Kind",
  "David Crosby: Remember My Name",
  "Dead Man Walking",
  "Deliverance",
  "Destry Rides Again",
  "Dr. Jekyll and Mr. Hyde",
  "El Dorado",
  "Everything Is Copy",
  "Eyimofe (This Is My Desire)",
  "Fatman",
  "Firecrackers",
  "Forbidden Planet",
  "Get Carter",
  "Girl Crazy",
  "Give Me Liberty",
  "Going My Way",
  "Goldfinger",
  "Good Time",
  "Hesburgh",
  "I Was a Simple Man",
  "In Jackson Heights",
  "In the Summers",
  "Invisible Hands",
  "Journey to Italy",
  "Lean on Pete",
  "Light from Light",
  "Linoleum",
  "M*A*S*H",
  "Minority Report",
  "Mountain",
  "Much Ado About Nothing",
  "Mystery Train",
  "Night Moves",
  "Nothing But a Man",
  "Once Upon a Time in the West",
  "One Cut of the Dead",
  "Personal Problems",
  "Portrait of Jason",
  "Relaxer",
  "Resolution",
  "Ride the High Country",
  "Rose Plays Julie",
  "Strange Darling",
  "Stray",
  "Sweet Smell of Success",
  "The Awful Truth",
  "The Friends of Eddie Coyle",
  "The Good, the Bad and the Ugly",
  "The Lavender Hill Mob",
  "The Levelling",
  "The Miracle Worker",
  "The Odd Couple",
  "The Old Man & the Gun",
  "The Philadelphia Story",
  "The Producers",
  "The Roaring Twenties",
  "The Settlers",
  "The Sundowners",
  "The Trip to Bountiful",
  "The Unknown Country",
  "The Yearling",
  "They Live by Night",
  "Turn Every Page: The Adventures of Robert Caro and Robert Gottlieb",
  "Wattstax",
  "We the Animals",
  "Wobble Palace",
  "You Hurt My Feelings",
  "Young Mr. Lincoln",
].to_set.freeze
